# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "dduportal/boot2docker"

  # Geoserver
  config.vm.network :forwarded_port, guest: 8080, host: 2207, auto_correct: true
  
    # postgis
  config.vm.network :forwarded_port, guest: 5432, host: 2201, auto_correct: true
  
end
